---
# tasks file for ansible-role-active-directory/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install Realm Daemon package"
  ansible.builtin.package:
    name: "{{ realmd_package }}"
    state: present

- name: "Discover required packages to join Domain"
  shell: realm discover {{ domain }}
  register: domain_discovery

- name: "Show Discovery"
  debug:
    var: domain_discovery

#- name: "Install required packages"
#  ansible.builtin.package:
#    name: "{{ item }}"
#    state: present
#    with_items: "{{ required_packages }}"

