---
# tasks file for ansible-role-active-directory/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install Realm Daemon package"
  ansible.builtin.package:
    name: "{{ realmd_package }}"
    state: present

- name: "Discover required packages to join Domain"
  shell: realm discover {{ domain }} | grep "required-package:" | awk '{ print $2}'
  register: required_packages

#- name: "Show Discovery"
#  debug:
#    msg: "{{ required_packages.stdout_lines | list }}"

- name: "Set required_packages facts"
  ansible.builtin.set_fact:
    required_packages: "{{ required_packages.stdout_lines | list }}"

#- name: "Install packages from required_packages discovery"
#  ansible.builtin.package:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ required_packages }}"

- name: "Check if machine is joined to the domain already"
  shell: realm -v list
  register: ad_check

- name: "Join active directoty domain"
  #shell: realm join -v -U {{ service_account }}@{{ domain.upper() }} --computer-ou='{{ ou }}' {{ domain }}
  shell: realm -v list
  when: ad_check.stderr | length != 0